/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.scircle;


import app.scircle.sec.cik.CentralIndexKeyLookUp;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Application {

    private static final Logger log = LoggerFactory.getLogger(Application.class);
    public static void main(String[] args) {
        log.info(CentralIndexKeyLookUp.getCikList(new String[]{"AAPL"}).toString());
        log.info(CentralIndexKeyLookUp.getCikList(new String[]{"MSFT"}).toString());
        log.info(CentralIndexKeyLookUp.getCikList(new String[]{"AAPL", "GOOGL"}).toString());
        log.info(String.valueOf(CentralIndexKeyLookUp.getCik("AAPL")));
        try {
            log.info(String.valueOf(CentralIndexKeyLookUp.getCik(null)));
        } catch (Exception e) {
            log.error("",e);
        }
        try {
            log.info(String.valueOf(CentralIndexKeyLookUp.getCikList(new String[]{"AAPL", "kjdasjd"})));
        } catch (Exception exception) {
            log.error("",exception);
        }
        try {
            log.info(String.valueOf(CentralIndexKeyLookUp.getCik("Bagaroo")));
        } catch (Exception e) {
            log.error("",e);
        }
    }
}
