/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.scircle;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SCircleApp {

    public static void main(String[] args) {
        SpringApplication.run(SCircleApp.class, args);
    }
}
