/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.scircle;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

import java.io.IOException;

@SpringBootApplication
public class SCircleApp {

    public static void main(String[] args)  {
        ConfigurableApplicationContext context = SpringApplication.run(SCircleApp.class, args);

        System.out.println(context.getEnvironment());

    }
}
